export type OperatorTaskStatus =
  | "pending"
  | "approved"
  | "running"
  | "completed"
  | "measured"
  | "learned"
  | "cancelled";

export type OperatorTaskPriority =
  | "critical"
  | "high"
  | "medium"
  | "low";

export type OperatorTaskCategory =
  | "operations"
  | "marketing"
  | "reviews"
  | "staffing"
  | "inventory"
  | "pricing"
  | "finance"
  | "maintenance"
  | "guest_experience"
  | "other";

export interface OperatorTask {
  id: string;

  locationName: string | null;

  title: string;
  description: string;

  category: OperatorTaskCategory;

  priority: OperatorTaskPriority;

  status: OperatorTaskStatus;

  autoExecutable: boolean;

  requiresApproval: boolean;

  estimatedImpact: number;

  confidence: number;

  createdAt: string;

  approvedAt?: string;
  startedAt?: string;
  completedAt?: string;
  measuredAt?: string;
  learnedAt?: string;

  metadata?: Record<string, unknown>;
}

export interface OperatorTaskQueue {
  pending: OperatorTask[];
  approved: OperatorTask[];
  running: OperatorTask[];
  completed: OperatorTask[];
  measured: OperatorTask[];
  learned: OperatorTask[];
}

export interface BuildTaskInput {
  executionPlan: any;
  executiveAI: any;
}

function generateId() {
  return crypto.randomUUID();
}

function priorityFromRisk(
  risk: string | undefined,
): OperatorTaskPriority {
  switch ((risk ?? "").toLowerCase()) {
    case "critical":
      return "critical";

    case "high":
      return "high";

    case "medium":
      return "medium";

    default:
      return "low";
  }
}

export function buildOperatorTask(
  input: BuildTaskInput,
): OperatorTask {
  const topTask =
    input.executionPlan?.topTask;

  const recommendation =
    input.executiveAI?.recommendation ??
    "Review restaurant operations.";

  const risk =
    input.executiveAI?.riskLevel;

  const confidence =
    input.executiveAI?.confidence ??
    60;

  return {
    id: generateId(),

    locationName:
      topTask?.locationName ??
      null,

    title:
      topTask?.title ??
      recommendation,

    description:
      topTask?.description ??
      "Generated by Executive AI.",

    category: "operations",

    priority:
      priorityFromRisk(risk),

    status: "pending",

    autoExecutable:
      topTask?.mode ===
      "automatic",

    requiresApproval:
      topTask?.mode !==
      "automatic",

    estimatedImpact:
      topTask?.estimatedImpact ??
      confidence,

    confidence,

    createdAt:
      new Date().toISOString(),

    metadata: {
      generatedBy:
        "TurnTableAI",
    },
  };
}

export function createQueue(
  tasks: OperatorTask[],
): OperatorTaskQueue {
  return {
    pending: tasks.filter(
      (t) => t.status === "pending",
    ),

    approved: tasks.filter(
      (t) => t.status === "approved",
    ),

    running: tasks.filter(
      (t) => t.status === "running",
    ),

    completed: tasks.filter(
      (t) => t.status === "completed",
    ),

    measured: tasks.filter(
      (t) => t.status === "measured",
    ),

    learned: tasks.filter(
      (t) => t.status === "learned",
    ),
  };
}

export function approveTask(
  task: OperatorTask,
): OperatorTask {
  return {
    ...task,
    status: "approved",
    approvedAt:
      new Date().toISOString(),
  };
}

export function startTask(
  task: OperatorTask,
): OperatorTask {
  return {
    ...task,
    status: "running",
    startedAt:
      new Date().toISOString(),
  };
}

export function completeTask(
  task: OperatorTask,
): OperatorTask {
  return {
    ...task,
    status: "completed",
    completedAt:
      new Date().toISOString(),
  };
}

export function measureTask(
  task: OperatorTask,
): OperatorTask {
  return {
    ...task,
    status: "measured",
    measuredAt:
      new Date().toISOString(),
  };
}

export function learnTask(
  task: OperatorTask,
): OperatorTask {
  return {
    ...task,
    status: "learned",
    learnedAt:
      new Date().toISOString(),
  };
}

export function cancelTask(
  task: OperatorTask,
): OperatorTask {
  return {
    ...task,
    status: "cancelled",
  };
}