import type {
  ProductionDecisionProvenance,
} from "@/lib/brain/decisionProvenance";

export type ExecutionMode =
  | "automatic"
  | "approval_required"
  | "monitor"
  | string;

export interface WorkflowStep {
  id?: string;
  title?: string;
  description?: string;
  status?: string;
  executionMode?: string;
  order?: number;
  successMetric?: string | null;
}

export interface OperatorWorkflow {
  id?: string;
  type?: string;
  title?: string;
  description?: string;

  locationName?: string | null;
  status?: string;
  priority?: string;
  executionMode?: string;

  confidence?: number | null;
  estimatedImpact?: number | null;

  currentStepId?: string | null;
  steps?: WorkflowStep[];

  successMetric?: string | null;
  expectedOutcome?: string | null;

  generatedAt?: string;
}

export interface ExecutionTask {
  id?: string;
  title?: string;
  description?: string;
  priority?: number | null;
  mode?: ExecutionMode;
  estimatedImpact?: number | null;
  confidence?: number | null;
}

export interface ExecutionPlan {
  summary?: string;
  mode?: ExecutionMode;
  topTask?: ExecutionTask | null;
  queue?: ExecutionTask[];
  generatedAt?: string;
}

export interface ExecutiveAI {
  headline?: string;
  recommendation?: string;
  riskLevel?: string;

  confidence?: number | null;

  whyNow?: string[];
  doNext?: string[];
  watchClosely?: string[];

  successMetric?: string;
  executiveSummary?: string;
}

export interface PlanningMove {
  id?: string;
  title?: string;
  actionType?: string;
  locationName?: string | null;

  urgency?: string;
  impact?: string;
  risk?: string;

  confidence?: number | null;
  roiScore?: number | null;
  priorityScore?: number | null;

  reason?: string;
  expectedOutcome?: string;

  executionWindow?: string;
  checklist?: string[];

  successMetric?: string;
}

export interface CausalHypothesis {
  id?: string;

  locationName?: string | null;

  category?: string;
  severity?: string;

  confidence?: string;
  confidenceScore?: number | null;

  cause?: string;
  explanation?: string;

  evidence?: string[];

  affectedMetrics?: string[];

  recommendedActions?: string[];

  whatWouldChangeMyMind?: string[];

  generatedAt?: string;
}

export interface RestaurantPrediction {
  id?: string;

  locationName?: string | null;

  horizon?: string;

  riskLevel?: string;

  confidence?: number | null;

  prediction?: string;

  expectedChange?: string;

  estimatedBusinessImpact?: string;

  leadingIndicators?: string[];

  ifIgnored?: string[];

  bestIntervention?: string[];

  metricsForecast?: {
    revenueChangePct?: number | null;
    refundChangePct?: number | null;
    ratingChange?: number | null;
    marginChangePct?: number | null;
    laborChangePct?: number | null;
  };

  generatedAt?: string;
}

export interface WorldSignal {
  id?: string;

  type?: string;

  label?: string;

  riskLevel?: string;

  confidence?: number | null;

  summary?: string;

  evidence?: string[];

  operatorImplication?: string;

  recommendedAdjustment?: string;
}

export interface WorldLocationModel {
  ok?: boolean;

  locationName?: string | null;

  summary?: string;

  externalPressureScore?: number | null;

  demandModifierPct?: number | null;

  laborModifierPct?: number | null;

  marginRiskModifierPct?: number | null;

  deliveryPressure?: string;

  signals?: WorldSignal[];

  assumptions?: string[];

  generatedAt?: string;
}
export type EvidenceSource =
  | "operator"
  | "pos"
  | "reviews"
  | "labor"
  | "inventory"
  | "reservations"
  | "other";
  export interface EvidenceReviewItem {
    /**
     * Stable evidence identifier generated by the Brain.
     */
    id?: string | null;
  
    /**
     * Decision question this evidence addresses.
     */
    question?: string | null;
  
    /**
     * Human-readable evidence statement shown to the operator.
     */
    statement: string;
  
    /**
     * Cognitive source, such as operator_memory or perception.
     */
    source?: string | null;
  
    /**
     * Evidence confidence. May be expressed as 0–1 or 0–100.
     */
    confidence?: number | null;
  
    /**
     * When the underlying observation occurred.
     */
    observedAt?: string | null;
  
    /**
     * Restaurant location associated with the evidence.
     */
    locationName?: string | null;
  }

  export interface EvidenceGapContext {
    /**
     * Current operating objective selected by the Brain.
     */
    objective?: string | null;
  
    /**
     * Investigate, test, contain, monitor, or act.
     */
    decisionMode?: string | null;
  
    /**
     * Highest-impact question that must still be resolved.
     */
    unresolvedQuestion: string;
  
    /**
     * Current leading explanation.
     */
    primaryHypothesis?: string | null;
  
    /**
     * Explanation of the leading hypothesis.
     */
    hypothesisDescription?: string | null;
  
    /**
     * Human-readable evidence already considered by the Brain.
     */
    currentEvidence: string[];
  
    /**
     * Structured evidence supplied through Operator Memory.
     *
     * Optional during migration so existing callers remain valid.
     */
    operatorEvidence?: EvidenceReviewItem[];
  
    /**
     * Information the Brain does not currently know.
     */
    unknowns: string[];
  
    /**
     * Questions completely resolved by available evidence.
     */
    resolvedUnknowns?: string[];
  
    /**
     * Questions addressed by evidence but not yet resolved
     * with sufficient confidence.
     */
    partiallyResolvedUnknowns?: string[];
  
    /**
     * Reasons preventing a stronger decision.
     */
    blockingReasons: string[];
  
    /**
     * Risks or tradeoffs identified during reasoning.
     */
    warnings: string[];
  
    /**
     * Current evidence coverage from 0–100.
     */
    evidenceCoverage?: number | null;
  
    /**
     * Optional restaurant location being investigated.
     */
    locationName?: string | null;
  }

export interface EvidenceSubmission {
  /**
   * Decision question this evidence addresses.
   */
  question: string;

  /**
   * Where the evidence came from.
   */
  source: EvidenceSource;

  /**
   * Evidence supplied by the operator or integration.
   */
  value: string;

  /**
   * Confidence in the supplied evidence from 0–100.
   */
  confidence: number;

  /**
   * When the underlying observation occurred.
   */
  observedAt: string;

  /**
   * Optional location associated with the evidence.
   */
  locationName?: string | null;

  /**
   * Optional context supplied by the operator.
   */
  notes?: string | null;
}
export interface DecisionTransitionData {
  type:
    | "changed_mind"
    | "reaffirmed"
    | string;

  changedMind: boolean;

  changeExplanationStatus?:
    | "not_needed"
    | "verified"
    | "verification_failed"
    | "previous_strategy_not_comparable"
    | string
    | null;

  changeExplanationVerified?:
    | boolean
    | null;

  changeProvenance?:
    | ProductionDecisionProvenance
    | null;

  previousActionId?:
    | string
    | null;

  previousStrategyId?:
    | string
    | null;

  previousStrategyTitle?:
    | string
    | null;

  currentStrategyId?:
    | string
    | null;

  currentStrategyTitle?:
    | string
    | null;

  locationName?:
    | string
    | null;

  previousDecisionAt?:
    | string
    | null;

  currentDecisionAt?:
    | string
    | null;

  currentDecisionReason?:
    | string
    | null;
}
export interface RecommendedActionData {
    /**
     * Primary recommendation from the AI.
     */
    title: string;
  
    /**
     * One or two sentence explanation shown directly beneath the title.
     */
    summary: string;

    decisionProvenance?:
  | ProductionDecisionProvenance
  | null;
  decisionTransition?:
  | DecisionTransitionData
  | null;
  
    /**
     * Confidence score from 0–100.
     */
    confidence: number;
  
    /**
     * Business impact score from 0–100.
     */
    impact: number;
  
    /**
     * Overall urgency level.
     */
    urgency: "low" | "medium" | "high";
  
    /**
     * Completion progress from 0–100.
     */
    progress: number;
  
    /**
     * Text shown on the primary action button.
     */
    actionLabel: string;
    /**
 * Prevents the primary action from being triggered.
 */
actionDisabled?: boolean;

/**
 * Indicates that the action is currently processing.
 */
actionBusy?: boolean;

/**
 * Temporary text shown while the action is processing.
 */
actionBusyLabel?: string;

/**
 * ID of the panel controlled by the primary action.
 */
actionControlsId?: string;
    /**
     * Optional secondary action.
     */
    secondaryLabel?: string;
  
    /**
     * Called when the user approves or executes the recommendation.
     */
    onApprove?: () => void | Promise<void>;
  
    /**
     * Called when the user wants additional context.
     */
    onViewDetails?: () => void | Promise<void>;
  }
  export interface WhyThisIsHappeningData {
      /**
   * Cognitive-state-aware heading for the explanation panel.
   */
  heading?: string;

  /**
   * Label used for the strongest current causal candidate.
   */
  primaryCauseLabel?: string;
    summary: string;
  
    primaryCause: string;
  
    explanation: string;
  
    category?: string;
  
    severity?: string;
  
    confidence: number;
  
    evidence: string[];
  
    recommendedActions: string[];
  
    whatWouldChangeMyMind: string[];
  }